version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    working_directory: /home/circleci/circleci/project/restorant_proj/restorant_proj/restorant_proj/restorant_proj/
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - run:
          working_directory: /home/circleci/circleci/project/restorant_proj/restorant_proj/restorant_proj/restorant_proj/
          name: install dependencies
          command: |
              pip install -r $(find . -name "requirements.txt")
      - python/save-cache
      - run:
          command: ./manage.py test
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
